accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.LogoutView.as_view(), name='user_logout'),
    path('profile/<slug:username>', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='user_unfollow'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>', views.PostUpdatView.as_view(), name='post_update'),
    path('post/create', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>,<int:comment_id>', views.CommentReplyView.as_view(), name='reply_comment')
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.slug} {self.created.date()}"

    def get_absolute_url(self):
        return reverse('home:post_detail', args=[self.id, self.slug])

    def delete_post(self):
        return reverse('home:post_delete', args=[self.id])

    def update_post(self):
        return reverse('home:post_update', args=[self.id])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

home/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['body']


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'home/index.html', {'posts': posts})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comment = Comment.objects.filter(post=self.post_instance, is_reply=False).all()
        return render(request, 'home/detail.html',
                      {'post': self.post_instance, 'comments': comment, 'form': self.form_class,
                       'reply_form': self.form_class_reply})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'your comment submitted successfully', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)
        return redirect()


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'post deleted successfully', 'success')
            return redirect('home:home')
        else:
            messages.error(request, 'you dont have permission to delete this post', 'danger')
        return redirect('home:post_detail', post_id=post_id, post_slug=post.slug)


class PostUpdatView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'you cant updated this post', 'danger')
            return redirect('home:post_detail', post_slug=post.slug, post_id=kwargs['post_id'])
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'you updated this post successfully', 'success')
            return redirect('home:post_detail', post.id, post.slug)


class PostCreateView(View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'])
            new_post.save()
            messages.success(request, 'you created a new post successfully', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)


class CommentReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        form = self.form_class(request.POST)
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = post
            reply.user = request.user
            reply.reply = comment
            reply.is_reply = True
            reply.save()
        return redirect('home:post_detail', post_id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}

{% block title %}
    create new post
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

home/templates/home/detail.html
{%  extends 'base.html' %}

{% block title %}
    {{ post.id }}
{% endblock %}

{% block content %}
    {% if request.user.id == post.user.id %}
        <a href="{{ post.delete_post }}" class="btn btn-danger">Delete</a>
        <a href="{{ post.update_post }}" class="btn btn-info">Update</a>
    {% endif %}
    <p><a href="{% url 'accounts:user_profile' post.user.username %}">{{ post.user.username }}</a> - {{ post.created|date:'M D, Y' }}</p>
    <p>{{ post.body }}</p><hr>
    <span>updated : {{ post.updated|date:'M D, Y - h:m:s' }}</span><hr/><hr/>
    {% if request.user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form><br>
    {% else %}
        <p class="alert alert-danger">for submit comment, you must log in firstly</p>
    {% endif %}
    {% for comment in comments %}
        <div class="card bg-muted text-dark">
            <p class="card-header">{{ comment.user }} | {{ comment.created | timesince }} ago</p>
            <p class="card-body">{{ comment.body }}</p>
            <hr>
            <form action={% url 'home:reply_comment' post.id comment.id %} method="post">
                {% csrf_token %}
                {{ reply_form.as_p }}
                <input type="submit" value="Send">
            </form>
            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <p class="card-header bg-primary p-2 m-3 pt-0">{{ reply.user }}<br>{{ reply.body }}</p><br>
                {% endfor %}
            {% endwith %}

        </div><br>
    {% empty %}
        <p class="text-primary">no comments yet!</p>
    {% endfor %}
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:4 }}</a>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block title %}
    update post
{% endblock %}

{% block content %}
    <form action="" method="post" class="col-md-5" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}